[package]
name = "simple-http-server"
version = "0.1.0"
authors = ["sypeng <sypeng@iflytek.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"