[package]
name = "rsa-encrypt-demo"
version = "0.1.0"
authors = ["psycode <psyucc@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.4"
base64 = "0.13.0"
rand = "0.8.3"
