[package]
name = "http_demo"
version = "0.1.0"
authors = ["sypeng <sypeng@iflytek.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.5.0"
log = "0.4.8"