[package]
name = "tree-demo"
version = "0.1.0"
authors = ["psycode <psyucc@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

